apiVersion: v1
kind: Secret
metadata:
  name: redis-credential
  namespace: infra
type: Opaque
stringData:
  ALLOW_EMPTY_PASSWORD: "false"
  REDIS_PASSWORD: password # In production, inject this via a vault/pipeline
