apiVersion: v1
kind: ServiceAccount
metadata:
  name: kong-controller
  namespace: kong
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kong-controller-clusterrole
rules:
  - apiGroups: [""]
    resources: ["endpoints", "nodes", "pods", "secrets", "services", "configmaps", "namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "ingressclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses/status", "ingressclasses/status"]
    verbs: ["update"]
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["gateways", "gatewayclasses", "httproutes", "grpcroutes", "referencegrants",
                "tcproutes", "tlsroutes", "udproutes", "backendtlspolicies"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["gateways/status", "gatewayclasses/status", "httproutes/status", "grpcroutes/status",
                "tcproutes/status", "tlsroutes/status", "udproutes/status", "backendtlspolicies/status"]
    verbs: ["update", "patch"]
  - apiGroups: ["configuration.konghq.com"]
    resources: ["kongplugins", "kongclusterplugins", "kongconsumers", "kongconsumergroups",
                "kongingresses", "kongupstreampolicies", "tcpingresses", "kongvaults"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["configuration.konghq.com"]
    resources: ["kongplugins/status", "kongclusterplugins/status", "kongconsumers/status",
                "kongconsumergroups/status", "kongingresses/status", "kongupstreampolicies/status",
                "tcpingresses/status", "kongvaults/status"]
    verbs: ["update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kong-controller-clusterrole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kong-controller-clusterrole
subjects:
  - kind: ServiceAccount
    name: kong-controller
    namespace: kong