apiVersion: v1
kind: ServiceAccount
metadata:
  name: kong-proxy
  namespace: kong
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kong-proxy-role
  namespace: kong
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kong-proxy-role-binding
  namespace: kong
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kong-proxy-role
subjects:
  - kind: ServiceAccount
    name: kong-proxy
    namespace: kong